- name: Subir imágenes a Azure Blob Storage
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Run tasks/other.yaml instead of 'main'
      import_role:
        name: Azure_Blob_Storage
        tasks_from: Upload_directory.yml