- name: Subir imágenes a Azure Blob Storage
  hosts: localhost
  gather_facts: false

  roles:
    - name: Create storage account
      azure_rm_storageaccount:
        resource_group: BlobTest
        name: testaccountnt001
        account_type: Standard_LRS

    - name: Create container and upload a file
      azure_rm_storageblob:
        resource_group: BlobTest
        storage_account_name: testaccountnt001
        container: prueba
        blob: migration/prueba.txt
        src: /home/ocduser/wendy/devops/ansible/prueba.txt

    - name: Download the file
      azure_rm_storageblob:
        resource_group: BlobTest
        storage_account_name: testaccountnt001
        container: prueba
        blob: migration/prueba.txt
        dest: /tmp/prueba.txt