- name: Subir imágenes a Azure Blob Storage
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Upload directory Blob_Storage
      import_role:
        name: Azure_Blob_Storage
        tasks_from: Upload_directory.yml

    - name: Delete XLS Files
      import_role:
        name: Azure_Blob_Storage
        tasks_from: Delete_files_xls.yml

    